name: moby2buy
recipe: drupal9
config:
  php: '7.4'
  composer_version: '2.0.7'
  via: apache:2.4
  webroot: .
  database: mysql:5.7
  drush: ^8
  xdebug: false
  config:
      php: config/php.ini
services:
  appserver:
    build:
      - composer install
